add_newline = false

[username]
style_user = "#B16286 bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)@[$hostname](bold #B16286) "
disabled = false

[directory]
style = "#458588"
truncation_length = 4
truncation_symbol = ".../"
