##################################################
#  ____ _____  _    ____  ____  _   _ ___ ____   #
# / ___|_   _|/ \  |  _ \/ ___|| | | |_ _|  _ \  #
# \___ \ | | / _ \ | |_) \___ \| |_| || || |_) | #
#  ___) || |/ ___ \|  _ < ___) |  _  || ||  __/  #
# |____/ |_/_/   \_\_| \_\____/|_| |_|___|_|     #
##################################################

add_newline = false

[username]
style_user = "#B16286 bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)@[$hostname](bold #B16286) "
disabled = false

[directory]
style = "#458588"
truncation_length = 4
truncation_symbol = ".../"
