add_newline = false

[username]
style_user = "#F4B8E4 bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)@[$hostname](bold #F4B8E4) "
disabled = false

[directory]
style = "#8CAAEE"
truncation_length = 4
truncation_symbol = ".../"
